[book]
authors = ["Shripad Krishna"]
language = "en"
multilingual = false
src = "src"
title = "Zero to Mastery: Rust"

[rust]
edition = "2024"

[output.html]
default-theme="rust"
preferred-dark-theme="rust"
